Section "Device"
    Identifier "Display"
    Driver "modesetting"
    Option "kmsdev" "/dev/dri/card0"
    Option "AccelMethod" "none"
EndSection
Section "Screen"
    Identifier "Screen"
    Device "Display"
    DefaultDepth 24
EndSection
Section "ServerFlags"
    Option "AutoAddDevices" "false"
    Option "BlankTime" "0"
    Option "StandbyTime" "0"
    Option "SuspendTime" "0"
    Option "OffTime" "0"
EndSection
